version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Deployment package"
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_handler.py
  post_build:
    commands:
      - echo "Uploading lambda function"
      - aws lambda update-function-code --function-name git-aws-lambda-automation --zip-file fileb://deployment_package.zip
      - echo "Done!"
